name: configuration conteneur
on: [push, workflow_dispatch]

jobs:

  deploy:
    runs-on: self-hosted   
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: donne la date pour test
      run: ls /home/ubuntu
